[package]
name = "multiply"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = { version = "=0.15.3" }

[dependencies]
risc0-zkvm = { version = "=0.15.3", default-features = false }
